# Generated by Django 4.0.1 on 2022-02-04 06:10

import ast
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerRegModel',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter First name', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'employer_details',
            },
        ),
        migrations.CreateModel(
            name='Internship_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stiepend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmployePostModel',
            fields=[
                ('Organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('Organization_name', models.CharField(help_text='Enter Organization name', max_length=100)),
                ('location', models.CharField(help_text='Location', max_length=100)),
                ('No_of_openings', models.IntegerField(help_text='No of openings ')),
                ('Start_Date', models.CharField(help_text='Start Date of Internship', max_length=100)),
                ('Skills', models.TextField()),
                ('Description', models.TextField()),
                ('Profile_picture', models.ImageField(null=True, upload_to='images/')),
                ('Posted_date', models.DateField(help_text='Posted Date', max_length=100)),
                ('Duration', models.ForeignKey(on_delete=ast.Pass, to='employerapp.duration')),
                ('Internship_type', models.ForeignKey(on_delete=ast.Pass, to='employerapp.internship_type')),
                ('Profile', models.ForeignKey(on_delete=ast.Pass, to='employerapp.profile')),
                ('Stiepend', models.ForeignKey(on_delete=ast.Pass, to='employerapp.stiepend')),
            ],
            options={
                'db_table': 'Internship_post_details',
            },
        ),
    ]
