# Generated by Django 4.0.1 on 2022-01-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployerID', models.IntegerField()),
                ('EmployerName', models.CharField(max_length=100)),
                ('OrganizationName', models.CharField(max_length=100)),
                ('OrganizationIdNumber', models.CharField(max_length=100)),
                ('InternshipCategory', models.CharField(max_length=100)),
                ('Internshipdescription', models.CharField(max_length=300)),
                ('MinStiepend', models.CharField(max_length=100)),
                ('OrganizationLocation', models.CharField(max_length=100)),
                ('InternshipDuration', models.CharField(max_length=100)),
                ('Workmode', models.CharField(max_length=100)),
            ],
        ),
    ]
