# Generated by Django 4.0.1 on 2022-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRegModel',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter First name', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployerPostModel',
        ),
    ]
