# Generated by Django 4.0.1 on 2022-02-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employepostmodel',
            old_name='status',
            new_name='emp_status',
        ),
    ]
