# Generated by Django 4.0.1 on 2022-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0002_employerregmodel_delete_employerpostmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employerregmodel',
            table='employer_details',
        ),
    ]
