# Generated by Django 4.0.1 on 2022-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_alter_employerregmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPostModel',
            fields=[
                ('Organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('Organization_name', models.CharField(help_text='Enter Organization name', max_length=100)),
                ('location', models.CharField(help_text='Location', max_length=100)),
                ('Profile', models.CharField(help_text=' Profile', max_length=100)),
                ('Internship_type', models.CharField(help_text='Internship Type', max_length=100)),
                ('No_of_openings', models.IntegerField(help_text='No of openings ', max_length=100)),
                ('Start_Date', models.CharField(help_text='Start Date of Internship', max_length=100)),
                ('Duration', models.DurationField(help_text=' Internship Duration', max_length=100)),
                ('Stiepend', models.IntegerField(help_text='Stiepend', max_length=100)),
                ('Skills', models.CharField(help_text=' Skills Required', max_length=100)),
                ('Description', models.CharField(help_text='Description', max_length=100)),
                ('Profile_picture', models.ImageField(help_text='Profile Picture', upload_to='')),
                ('Posted_date', models.DateTimeField(help_text=' Posted Date', max_length=100)),
            ],
            options={
                'db_table': 'Post_details',
            },
        ),
    ]
