# Generated by Django 4.0.1 on 2022-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregmodel',
            name='panpic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
