# Generated by Django 4.0.1 on 2022-03-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0004_employerregmodel_panpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerregmodel',
            name='pan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
