# Generated by Django 4.0.1 on 2022-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0004_employerpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Description',
            field=models.CharField(help_text='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='No_of_openings',
            field=models.IntegerField(help_text='No of openings '),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Skills',
            field=models.CharField(help_text=' Skills Required', max_length=500),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Stiepend',
            field=models.IntegerField(help_text='Stiepend'),
        ),
    ]
