# Generated by Django 4.0.1 on 2022-02-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0005_alter_employerpostmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Duration',
            field=models.DurationField(help_text='Internship Duration', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Posted_date',
            field=models.DateField(help_text='Posted Date', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Profile',
            field=models.Field(help_text='Profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='Skills',
            field=models.CharField(help_text='Skills Required', max_length=500),
        ),
        migrations.AlterField(
            model_name='employerpostmodel',
            name='location',
            field=models.TextField(help_text='Location', max_length=100),
        ),
    ]
