# Generated by Django 4.0.1 on 2022-02-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0007_alter_employerpostmodel_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerPostModel',
            new_name='EmployePostModel',
        ),
    ]
