# Generated by Django 4.0.1 on 2022-02-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0008_rename_employerpostmodel_employepostmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employepostmodel',
            table='post_details',
        ),
    ]
