# Generated by Django 4.0.1 on 2022-02-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0009_alter_employepostmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employepostmodel',
            table='Internship_post_details',
        ),
    ]
