# Generated by Django 4.0.1 on 2022-02-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
