# Generated by Django 4.0.1 on 2022-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplyModel',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Percentage', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pcode', models.CharField(max_length=100)),
                ('Resume', models.ImageField(null=True, upload_to='images/')),
                ('Applied_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'applied_details',
            },
        ),
        migrations.CreateModel(
            name='StudentRegModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
