# Generated by Django 4.0.1 on 2022-02-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsavedmodel',
            old_name='No_of_openings',
            new_name='internship_id',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Internship_type',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Organization_name',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Pan',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Posted_date',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Profile_picture',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Start_Date',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Stiepend',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='Year_of_establishment',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='employer_id',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentsavedmodel',
            name='website',
        ),
    ]
