# Generated by Django 4.0.1 on 2022-01-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentregmodel',
            table='student_details',
        ),
    ]
