# Generated by Django 4.0.1 on 2022-03-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
        ('userapp', '0002_rename_no_of_openings_studentsavedmodel_internship_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplymodel',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employerapp.employepostmodel'),
        ),
    ]
