# Generated by Django 4.0.1 on 2022-03-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
        ('userapp', '0003_studentapplymodel_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplymodel',
            name='emp_id',
            field=models.ForeignKey(blank=True, db_column='emp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employerapp.employepostmodel'),
        ),
    ]
