# Generated by Django 4.0.1 on 2022-03-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
        ('userapp', '0004_alter_studentapplymodel_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplymodel',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='studentapplymodel',
            name='internship_id',
            field=models.ForeignKey(blank=True, db_column='internship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employerapp.employepostmodel'),
        ),
    ]
