# Generated by Django 4.0.1 on 2022-03-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
        ('userapp', '0006_alter_studentapplymodel_internship_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplymodel',
            name='internship_id',
        ),
        migrations.AddField(
            model_name='studentapplymodel',
            name='internship',
            field=models.ForeignKey(db_column='internship_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='employerapp.employepostmodel'),
        ),
    ]
