# Generated by Django 4.0.1 on 2022-03-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0003_employepostmodel_mobile'),
        ('userapp', '0007_remove_studentapplymodel_internship_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsavedmodel',
            name='internship_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern', to='employerapp.employepostmodel'),
        ),
    ]
